'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ReactNode } from 'react';

interface HelpDialogProps {
  children: ReactNode;
}

export function HelpDialog({ children }: HelpDialogProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-[425px] md:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Help & Information</DialogTitle>
          <DialogDescription>
            Everything you need to know to use the RagInfo app.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="max-h-[60vh] pr-6">
            <div className="space-y-6 text-sm text-muted-foreground">
                <section>
                    <h3 className="font-semibold text-lg text-foreground mb-2">Functionality</h3>
                    <p>
                        This application allows you to have conversations with your PDF documents.
                        It uses a Retrieval-Augmented Generation (RAG) architecture powered by large language models
                        to provide answers based on the content of the files you upload.
                    </p>
                </section>

                <section>
                    <h3 className="font-semibold text-lg text-foreground mb-2">How to Use the App</h3>
                    <ol className="list-decimal list-inside space-y-2">
                        <li>
                            <strong className="font-medium text-foreground">Configure your API Key:</strong> Navigate to the <code className="bg-muted px-1 py-0.5 rounded">Settings</code> page. Enter your Google AI API Key and select an AI model. Your key is encrypted and stored securely in your browser&apos;s local storage.
                        </li>
                        <li>
                            <strong className="font-medium text-foreground">Upload Documents:</strong> Go to the <code className="bg-muted px-1 py-0.5 rounded">Files</code> page. Drag and drop your PDF files into the upload area or click to select them. The app will process each file, extract the text, and add it to its knowledge base.
                        </li>
                        <li>
                            <strong className="font-medium text-foreground">Start Chatting:</strong> Head over to the <code className="bg-muted px-1 py-0.5 rounded">Chat</code> page. You can now ask questions related to the content of your uploaded documents.
                        </li>
                        <li>
                            <strong className="font-medium text-foreground">Manage Files:</strong> You can delete uploaded files from the <code className="bg-muted px-1 py-0.5 rounded">Files</code> page at any time. Deleting a file removes it from the AI&apos;s knowledge base.
                        </li>
                    </ol>
                </section>
                
                <section>
                    <h3 className="font-semibold text-lg text-foreground mb-2">Disclaimer</h3>
                    <p>
                        The responses generated by the AI are based on the information present in your uploaded documents and can sometimes be inaccurate or incomplete. Always verify critical information.
                    </p>
                    <p className="mt-2">
                        Your Google AI API key and chat history are stored in your browser&apos;s local storage. The API key is encrypted for security. Clearing your browser data will remove all your settings and history.
                    </p>
                </section>
            </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
